# Generated by Django 4.1.13 on 2024-06-21 10:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('airline_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('alias', models.CharField(max_length=255)),
                ('iata', models.CharField(max_length=255)),
                ('callsign', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('active', models.CharField(max_length=255)),
                ('icao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('iata_code', models.CharField(max_length=255)),
                ('icao_code', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('airport_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('iata', models.CharField(max_length=255)),
                ('icao', models.CharField(max_length=255)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.FloatField()),
                ('timezone', models.CharField(max_length=255)),
                ('dst', models.CharField(max_length=255)),
                ('db_timezone', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('airline', models.CharField(max_length=255)),
                ('airline_id', models.CharField(max_length=255)),
                ('source_airport', models.CharField(max_length=255)),
                ('source_airport_id', models.CharField(max_length=255)),
                ('destination_airport', models.CharField(max_length=255)),
                ('destination_airport_id', models.CharField(max_length=255)),
                ('stops', models.IntegerField()),
                ('equipment', models.CharField(max_length=255)),
            ],
        ),
    ]
